meta:
  name: piloth
  version: 1
  release: 0
  arch: amd64
  maintainer: AtosSE <no-reply@atos.net>
  license: Apache 2.0
  url: atos.net
  vendor: AtosSE
  summary: |-
    Pilot automation service
  description: |-
    Powerfull automation service to deliver today's Microservices
files:
  generic:
    - destination: /bin/piloth
      source: /Users/eduardgevorkyan/Desktop/pilot/piloth
      owner: root
      group: root
    - destination: /lib/systemd/system/piloth.service
      source: /Users/eduardgevorkyan/Desktop/pilot/systemd/piloth.service
      owner: root
      group: root
  config:
    - destination: /home/pilot/.config/pilot/.userkey
      source: /Users/eduardgevorkyan/Desktop/pilot/.userkey
      mode: 0600
      owner: pilot
      group: pilot
preinstall:
  - echo pilot installation started;
  - useradd -m -s /bin/bash pilot
  - mkdir -p /home/pilot/.config/pilot
  - chown pilot:pilot -R /home/pilot/
postinstall:
  - echo pilot installation finished successfully;
  - echo 'pilot ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/pilot
  - chmod 0440 /etc/sudoers.d/pilot
  - chown pilot:pilot /home/pilot/.config/pilot/.userkey
  - systemctl daemon-reload
  - systemctl enable --now piloth
preuninstall:
  - echo pilot uninstalling;
  - systemctl stop piloth
postuninstall:
  - echo pilot uninstalled successfully;
  - system daemon-reload
signature:
  type: origin
  private_key: gatblau-priv.asc
  pass_phrase: h3783T@dF%an

